export const movies = [
    { title: 'The Shawshank Redemption', image: 'img/movies/1.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/2.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/3.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/4.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/5.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/6.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/7.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/8.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/9.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/10.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/11.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/12.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/13.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/14.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/15.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/16.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/17.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/18.png' },
]