export const movies = [
    { title: 'The Godfather', image: 'img/movies/1.png' },
    { title: 'The Dark Knight', image: 'img/movies/2.png' },
    { title: '12 Angry Men', image: 'img/movies/3.png' },
    { title: 'Pulp Fiction', image: 'img/movies/4.png' },
    { title: 'The Lord of the Rings: The Return', image: 'img/movies/5.png' },
    { title: 'Il buono, il brutto, il cattivo', image: 'img/movies/6.png' },
    { title: 'Fight Club', image: 'img/movies/7.png' },
    { title: 'Schindler\'s List', image: 'img/movies/8.png' },
    { title: '2. The Godfather', image: 'img/movies/9.png' },
    { title: '2. The Godfather', image: 'img/movies/10.png' },
    { title: 'Star Wars', image: 'img/movies/11.png' },
    { title: 'Inception', image: 'img/movies/12.png' },
    { title: 'One Flew Over the Cuckoo\'s Nest', image: 'img/movies/13.png' },
    { title: 'Goodfellas', image: 'img/movies/14.png' },
    { title: 'The Matrix', image: 'img/movies/15.png' },
    { title: 'The Lord of the Rings', image: 'img/movies/16.png' },
    { title: 'The Godfather Part II', image: 'img/movies/17.png' },
    { title: 'The Shawshank Redemption', image: 'img/movies/18.png' },
]