export const movies = [
    { title: 'The Godfather', image: 'img/movies/1.png', rating: 4.2 },
    { title: 'The Dark Knight', image: 'img/movies/2.png', rating: 3.8 },
    { title: '12 Angry Men', image: 'img/movies/3.png', rating: 4.5 },
    { title: 'Pulp Fiction', image: 'img/movies/4.png', rating: 3.9 },
    { title: 'The Lord of the Rings: The Return', image: 'img/movies/5.png', rating: 4.1 },
    { title: 'Il buono, il brutto, il cattivo', image: 'img/movies/6.png', rating: 4.3 },
    { title: 'Fight Club', image: 'img/movies/7.png', rating: 4.0 },
    { title: 'Schindler\'s List', image: 'img/movies/8.png', rating: 4.4 },
    { title: '2. The Godfather', image: 'img/movies/9.png', rating: 3.7 },
    { title: '2. The Godfather', image: 'img/movies/10.png', rating: 4.6 },
    { title: 'Star Wars', image: 'img/movies/11.png', rating: 3.5 },
    { title: 'Inception', image: 'img/movies/12.png', rating: 4.0 },
    { title: 'One Flew Over the Cuckoo\'s Nest', image: 'img/movies/13.png', rating: 4.2 },
    { title: 'Goodfellas', image: 'img/movies/14.png', rating: 3.9 },
    { title: 'The Matrix', image: 'img/movies/15.png', rating: 4.3 },
    { title: 'The Lord of the Rings', image: 'img/movies/16.png', rating: 4.1 },
    { title: 'The Godfather Part II', image: 'img/movies/17.png', rating: 4.5 },
    { title: 'The Shawshank Redemption', image: 'img/movies/18.png', rating: 4.4 },
];